#!/usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# this is the shell script to start Hoya deploying an application
# Usage: hoya <action> <commands>

# The env variable HOYA_JVM_OPTS can be used to override
# the default JVM opts

function usage
{
  echo "Usage: hoya <action> <arguments>"
  echo ""
}

# Hoya works out its own location 
this="${BASH_SOURCE-$0}"
bindir=$(cd -P -- "$(dirname -- "$this")" && pwd -P)
script="$(basename -- "$this")"
this="$bin/$script"

# lib directory is one up; it is expected to contain 
# hoya.jar and any other dependencies that are not in the
# standard Hadoop classpath

hoya_home="${bindir}/.."
hoya_home=`cd -P "${hoya_home}" && pwd -P`

libdir="${hoya_home}/lib"
libdir=`cd -P "${libdir}" && pwd -P`


confdir="${hoya_home}/conf"

# normalize the conf dir so it can be passed down
confdir=`cd -P "${confdir}" && pwd -P`
confdir=${HOYA_CONF_DIR:-confdir}


hoya_jvm_opts="-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Xmx256m -Dhoya.confdir=${confdir}"
hoya_jvm_opts=${HOYA_JVM_OPTS:-hoya_jvm_opts}

hoya_classpath="${libdir}/*:${confdir}"

launcher=org.apache.hadoop.hoya.Hoya


echo "classpath is \"${hoya_classpath}\""
export CLASSPATH="${hoya_classpath}"
echo ""

echo "command is java ${hoya_jvm_opts} --classpath \"${hoya_classpath}\" ${launcher} $@"
echo ""
echo ""
exec java ${hoya_jvm_opts}  ${launcher} $@
